"""New Column added

Revision ID: 13c8032c7368
Revises: 00e14d21619d
Create Date: 2022-06-22 20:57:33.384206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c8032c7368'
down_revision = '00e14d21619d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('C', sa.Column('question_link', sa.String(), nullable=True))
    op.add_column('cpp', sa.Column('question_link', sa.String(), nullable=True))
    op.add_column('java', sa.Column('question_link', sa.String(), nullable=True))
    op.add_column('python', sa.Column('question_link', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['profile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('python', 'question_link')
    op.drop_column('java', 'question_link')
    op.drop_column('cpp', 'question_link')
    op.drop_column('C', 'question_link')
    # ### end Alembic commands ###
