"""third commit

Revision ID: 3e8841b3c0b8
Revises: 24ace93e32ca
Create Date: 2022-04-27 21:51:01.602644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8841b3c0b8'
down_revision = '24ace93e32ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('contest_name', sa.String(), nullable=True))
    op.add_column('participants', sa.Column('contest_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'contest_id')
    op.drop_column('participants', 'contest_name')
    # ### end Alembic commands ###
