"""Verify Email

Revision ID: 420072390149
Revises: a0d96510a15e
Create Date: 2022-05-21 00:44:55.640767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420072390149'
down_revision = 'a0d96510a15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_verified_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified_on')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
