"""third commit 1

Revision ID: 4b247b8aaf56
Revises: 3e8841b3c0b8
Create Date: 2022-04-27 21:55:13.166059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b247b8aaf56'
down_revision = '3e8841b3c0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'contest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('contest', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
