"""Updating Profile Picture Column in Table

Revision ID: 67b350172bc0
Revises: 420072390149
Create Date: 2022-06-18 16:53:04.778948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b350172bc0'
down_revision = '420072390149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['profile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'profile')
    # ### end Alembic commands ###
