"""User program column added

Revision ID: 9733b590cbc9
Revises: 67b350172bc0
Create Date: 2022-06-18 22:44:52.675351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9733b590cbc9'
down_revision = '67b350172bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('program', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['profile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'program')
    # ### end Alembic commands ###
